 const constants = {
    AUTHENTICATED: 'USER_AUTHENTICATED',
    UNAUTHENTICATED: 'USER_UNAUTHENTICATED',
    AUTHENTICATED_ERROR: 'AUTHENTICATED_ERROR',
    POSTS_RECEIVED: 'POSTS_RECEIVED',
    LOGOUT: 'USER_LOGGING_OUT',
    LOGGED_IN: 'USER_LOGGEDIN',
    INCREMENT_POST_LIKES: 'INCREMENT_POST_LIKES'
};

export default constants;